services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cambly_octane
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - APP_KEY=${APP_KEY}       # Ensure this is in your .env
      - APP_ENV=${APP_ENV}       # Ensure this is in your .env
      - APP_DEBUG=${APP_DEBUG}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=cambly
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/app
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    # Fix for permission issues since Bitnami uses user 1001
    user: "root" 

  db:
    image: mariadb:10.6
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-storage-engine=InnoDB
      --innodb-file-per-table=1
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=cambly
      # - MYSQL_USER=${DB_USERNAME}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=https://cambly.devifyo.cloud/dbase/
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db

volumes:
  db_data:
